template-repository: "jebel-quant/rhiza"
template-branch: "main"
include: |
  .github
  .devcontainer
  .editorconfig
  .gitignore
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Makefile
  docker
  pytest.ini
  ruff.toml
exclude: |
  .github/template.yml
