## Makefile (repo-owned) -- generated by `uvx rhiza-task shim > Makefile`
#
# This replaces `.rhiza/rhiza.mk` and the ten fragments in `.rhiza/make.d/`: 1023 synced
# lines, at a template tag, for a dozen lines pinned to a package version.
#
# `make` stays the front door. It is what a stranger types in an unfamiliar repository,
# what a decade of muscle memory reaches for, and what keeps a consumer pinned to an older
# reusable workflow working unchanged. It just no longer *contains* anything.
#
# RHIZA_TASK is the entire version contract. Bumping it is the migration that used to be
# `/rhiza:update` re-syncing eleven .mk files and reconciling whatever had been shadowed.
RHIZA_TASK ?= rhiza-task@0.2.0

# The one thing the shim cannot delegate to the CLI: uv itself, because uv is what runs
# the CLI. `bootstrap.mk` had an `install-uv` target for exactly this, and the make layer's
# contract was that `make <anything>` works on a bare runner -- rhiza's own `pre-commit` job
# runs `make fmt` with no `astral-sh/setup-uv` step, and `ubuntu-latest` ships no uv. A shim
# that only ran `uvx` would turn a required status check red on the day a repo migrated.
#
# So the bootstrap survives, minus the parts the CLI took over: no `bin/uv`, no clean-up,
# just the one binary needed to reach the pin above.
INSTALL_DIR ?= $(abspath ./bin)
UVX ?= $(shell command -v uvx 2>/dev/null || echo $(INSTALL_DIR)/uvx)

# --- mother-repo addition: the PATH export the shim drops, which it must not.
#
# The shipped shim says "no PATH export" and reaches the CLI by absolute path, which is
# enough to *start* it and not enough to let it work. rhiza-task's task bodies shell out to
# bare `uv` and `uvx` (`uv.py`'s `uv_run`/`uvx` helpers), so on a runner with no uv the shim
# provisions ./bin/uvx, invokes it, and then the CLI dies with
#
#   FileNotFoundError: [Errno 2] No such file or directory: 'uvx'
#
# which is what turned the required `Pre-commit hooks` check red on the first push of this
# migration: that job runs `make fmt` with no astral-sh/setup-uv step. `bootstrap.mk`
# exported PATH for exactly this reason.
#
# Prepended rather than appended, so the bootstrapped binary is the one every gate uses --
# otherwise a runner with an older uv earlier on PATH would resolve differently from a bare
# one, and the pin above would stop being the whole version contract.
#
# Reported upstream as Jebel-Quant/rhiza-task#19; remove when the shipped shim carries it.
export PATH := $(INSTALL_DIR):$(PATH)

.DEFAULT_GOAL := help

# `help` is the shim's, with one mother-repo addition: the CLI enumerates its own tasks
# and cannot know about the repo-owned targets at the foot of this file, so they are
# listed too. Without the second half `make help` silently omits `e2e` and `sync-self`.
help: $(UVX)
	@$(UVX) $(RHIZA_TASK) list
	@printf '\nRepo-owned targets (this file):\n'
	@grep -hE '^[a-zA-Z0-9_-]+:.*##' $(MAKEFILE_LIST) | sed -e 's/:.*##/ -- /' -e 's/^/  /'

# `%:` matches any target make cannot otherwise resolve. Two caveats, both survivable: a
# typo is routed here too (the CLI's "unknown task" error is the backstop), and a task
# needing flags wants `uvx rhiza-task <task> --flag` directly. `.PHONY` cannot name unknown
# targets, so a *file* sharing a task's name would shadow it -- none do.
%: $(UVX)
	@$(UVX) $(RHIZA_TASK) $@

# Named as a file rather than a phony `install-uv`, so make's own up-to-date check is the
# idempotence: when uvx is on PATH this is an existing file with no prerequisites and
# nothing runs, and when it is not, this rule is the only way the file can come into being.
# There is no probe to get wrong and no second invocation that re-downloads.
#
# The target is `$(UVX)` and not `$(INSTALL_DIR)/uvx` because it has to exist as an
# explicit rule in *both* cases: with no rule of its own, an on-PATH uvx is matched by the
# catch-all below, whose prerequisite is that same file, and every invocation opens with
# `make: Circular /usr/local/bin/uvx <- /usr/local/bin/uvx dependency dropped.`
#
# `$(@D)` rather than `$(INSTALL_DIR)`: the installer writes where the binary was expected,
# so an overridden `UVX=/somewhere/uvx` provisions /somewhere rather than silently
# downloading to ./bin and then running nothing.
$(UVX):
	@echo "[INFO] uv not found; installing into $(@D)"
	@curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR="$(@D)" sh >/dev/null

# Repo-specific one-offs live here, where they always belonged, and win over the catch-all
# because an explicit rule beats a pattern rule. This is what `local.mk` was for -- and a
# repository that carried its *own* fragment under `.rhiza/make.d/` has to move it here
# before deleting `rhiza.mk`, which is the file whose `-include` was reaching it.
-include local.mk

# An included makefile is also a target make tries to *remake* before running anything, and
# with a match-anything rule in scope that attempt is routed to the CLI -- so every single
# invocation used to begin with "unknown task: local.mk". An explicit rule with an empty
# recipe satisfies the remake attempt silently.
local.mk: ;

# The Makefile needs the same treatment now, and did not before. A match-anything rule with
# no prerequisites cannot make an existing Makefile out of date, so the remake attempt was a
# no-op; `$(UVX)` is a prerequisite that a cold checkout *creates*, which makes it newer than
# the Makefile, which makes the Makefile out of date -- so make remade it by running
# `uvx rhiza-task Makefile`, and the first `make <anything>` on a machine without uv died
# with "unknown task: Makefile" right after installing uv. An empty recipe ends that too.
Makefile: ;

# ==============================================================================
# Mother-repo-only targets (rhiza itself)
#
# These were `.rhiza/make.d/bundles.mk`, a fragment no bundle shipped. They land here
# rather than in `local.mk` for one reason: `local.mk` is gitignored (.gitignore:121) and
# CI invokes two of them — `make e2e` from rhiza_e2e.yml and `make gitlab-docker-test`
# from rhiza_weekly.yml — so they need a committed home. An explicit rule beats the `%:`
# pattern rule above, so they take precedence over the CLI delegation; `install` as a
# prerequisite still resolves through it.
#
# The folder accumulators this fragment also carried (TYPECHECK_FOLDERS, BANDIT_FOLDERS,
# DOCSTRING_FOLDERS, DEPTRY_FOLDERS, SEMGREP_FOLDERS, COVERAGE_FOLDERS += utils) are gone,
# replaced by `source-folder = "utils"` in pyproject.toml's [tool.rhiza-task]. They existed
# because this repo ships configuration and has no src/, so SOURCE_FOLDER matched nothing
# and five gates measured nothing (#1505, #1511, #1516). The CLI reads a single
# source_folder, and `utils` is this repo's only non-test Python, so one setting replaces
# six appends. tests/utils/test_gate_scope.py pins the outcome either way.
# ==============================================================================

.PHONY: explain-bundles sync-self sync-self-check e2e gitlab-docker-test rhiza-test

# `uv` as well as `uvx`: the astral installer writes both into the same directory, so once
# $(UVX) exists this does too. The empty recipe satisfies make's remake attempt, the same
# trick the shim uses for `local.mk`.
UV ?= $(shell command -v uv 2>/dev/null || echo $(INSTALL_DIR)/uv)
$(UV): $(UVX) ;

# Which end-to-end modules `make e2e` runs. One per language layer, so CI can give each its
# own job (and its own toolchain) by narrowing this:
#   make e2e E2E_ARGS=tests/e2e/test_go_layer_e2e.py
E2E_ARGS ?= tests/e2e

explain-bundles: $(UV) ## print all bundles and profiles with descriptions and dependencies
	@$(UV) run utils/explain_bundles.py

sync-self: $(UV) ## relink root dogfood copies as symlinks into bundles/ (mother repo only)
	@$(UV) run utils/link_dogfood.py

# The local drift check, for use before committing a new bundle file. In CI the same
# invariant is asserted by tests/bundles/test_bundle_dogfood_symlinks.py inside `make test`
# — using link_dogfood's own carve-out predicate and bundle index, so the two cannot
# disagree. No workflow runs this target (#1532).
sync-self-check: $(UV) ## fail if any dogfood symlink is stale/missing without writing (local drift check)
	@$(UV) run utils/link_dogfood.py --check

# The language-layer end-to-end suite: assemble a profile into a temp directory, scaffold
# the smallest project the layer should be green on, and run every gate for real. Opt-in
# because it drives real toolchains and takes minutes per layer; a layer whose compiler is
# absent skips rather than fails, so `make e2e` on a machine with no Go installed still
# exercises the layers it can.
#
# `make test` deliberately excludes it: the matrix would pay for it on every OS and Python
# version. .github/workflows/rhiza_e2e.yml is where all three actually run.
#
# pytest-timeout is provisioned here rather than declared: without it pytest ignores both
# pytest.ini's `timeout` and the suite's marker — silently, so a hung gate would run until
# the CI job's own timeout killed it with no indication of which gate hung.
e2e: install $(UV) ## run the language-layer end-to-end suite against real toolchains (opt-in)
	@printf "\033[36m[INFO] Running end-to-end suite: $(E2E_ARGS)\033[0m\n"
	@RHIZA_E2E=1 $(UV) run --with pytest-timeout pytest $(E2E_ARGS) -v

# The Docker-backed half of the GitLab suite: run a real job under gitlab-ci-local against
# the pinned $UV_IMAGE from bundles/gitlab/.gitlab-ci.yml.
#
# Opt-in for the same reason `e2e` is — it pulls a large image and needs Docker and Node —
# but opt-in without an entry point is how it came to run nowhere at all (#1528):
# RHIZA_GITLAB_DOCKER was set by no workflow, no target and no .env, so the one check that
# the pinned image still pulls and runs was skipped in every environment. rhiza_weekly.yml
# calls this target; the cadence matches the cost.
#
# `-m gitlab_exec` selects by marker (registered in tests/conftest.py) rather than by node
# id, so a second Docker-backed test is picked up by writing it, not by editing this recipe.
gitlab-docker-test: install $(UV) ## run the Docker-backed GitLab job test against the pinned image (opt-in)
	@printf "\033[36m[INFO] Running the Docker-backed GitLab job test\033[0m\n"
	@RHIZA_GITLAB_DOCKER=1 $(UV) run pytest tests/bundles/test_gitlab_ci.py -m gitlab_exec -v

# `rhiza-test` is wrapped rather than delegated, for one reason the CLI cannot yet cover.
#
# pytest-rhiza's `test_docstrings` takes its scope from the RHIZA_DOCTEST_FOLDERS
# environment variable, falling back to SOURCE_FOLDER in `.rhiza/.env` and then to `src`.
# `quality.mk` used to export it from DOCSTRING_FOLDERS; rhiza-task does not, and it cannot
# read `[tool.rhiza-task] source-folder` either. So on a bare delegation the check reported
#
#   SKIPPED  No doctest folder found (looked for: src)
#
# and the gate still said `ok rhiza-test` — #1517 exactly: this repo's only doctest examples
# unchecked, silently, behind a green gate. `.rhiza/.env` cannot carry it because that file
# is gitignored, so CI would never see it.
#
# Remove this wrapper once rhiza-task passes source_folder through to the check
# (Jebel-Quant/rhiza-task#18). tests/utils/test_gate_scope.py fails if the skip returns.
rhiza-test: $(UVX) ## run the rhiza repository checks, with this repo's doctest scope
	@RHIZA_DOCTEST_FOLDERS="$(shell $(UVX) $(RHIZA_TASK) print source_folder)" \
		$(UVX) $(RHIZA_TASK) rhiza-test
