## Makefile (repo-owned) -- generated by `uvx rhiza-task shim > Makefile`
#
# This replaces `.rhiza/rhiza.mk` and the sixteen fragments in `.rhiza/make.d/`: 1481 synced
# lines, at a template tag, for a dozen lines pinned to a package version. The folder is gone
# entirely as of rhiza-task 0.3.0, which took over the last five (docker, github, lfs, paper,
# presentation) -- see Jebel-Quant/rhiza-task#22.
#
# `make` stays the front door. It is what a stranger types in an unfamiliar repository,
# what a decade of muscle memory reaches for, and what keeps a consumer pinned to an older
# reusable workflow working unchanged. It just no longer *contains* anything.
#
# RHIZA_TASK is the entire version contract. Bumping it is the migration that used to be
# `/rhiza:update` re-syncing eleven .mk files and reconciling whatever had been shadowed.
RHIZA_TASK ?= rhiza-task@0.3.1

# The one thing the shim cannot delegate to the CLI: uv itself, because uv is what runs
# the CLI. `bootstrap.mk` had an `install-uv` target for exactly this, and the make layer's
# contract was that `make <anything>` works on a bare runner -- rhiza's own `pre-commit` job
# runs `make fmt` with no `astral-sh/setup-uv` step, and `ubuntu-latest` ships no uv. A shim
# that only ran `uvx` would turn a required status check red on the day a repo migrated.
#
# So the bootstrap survives, minus the parts the CLI took over: no `bin/uv`, no clean-up,
# just the one binary needed to reach the pin above -- and the PATH export, because
# reaching the CLI is not the same as letting it run. Every task body shells out to a bare
# `uv` or `uvx` (`uv.py` resolves both with `shutil.which`, which reads the PATH it
# inherits), so provisioning `./bin/uvx` and then not exporting `./bin` gets as far as the
# first gate that shells out and dies with `FileNotFoundError: 'uvx'` -- after a bootstrap
# that looked like it worked. `version`, `print` and `list` are pure-CLI and stay green,
# which is how this reached a required status check: the `pre-commit` job runs `make fmt`
# with no astral-sh/setup-uv step, and `Pre-commit hooks` is required in
# .github/rulesets/main-branch-protection.json.
#
# Prepended, not appended: with `$(INSTALL_DIR)` last, a runner carrying an older uv
# earlier on PATH resolves differently from a bare one, and `RHIZA_TASK` quietly stops
# being the whole version contract the header above claims it is.
#
# This block was a mother-repo addition until 0.3.1 (Jebel-Quant/rhiza-task#19); the
# shipped shim carries it now, so the two are one file again.
INSTALL_DIR ?= $(abspath ./bin)
UVX ?= $(shell command -v uvx 2>/dev/null || echo $(INSTALL_DIR)/uvx)
export PATH := $(INSTALL_DIR):$(PATH)

.DEFAULT_GOAL := help

# `help` is the shim's, with one mother-repo addition: the CLI enumerates its own tasks
# and cannot know about the repo-owned targets at the foot of this file, so they are
# listed too. Without the second half `make help` silently omits `e2e` and `sync-self`.
help: $(UVX)
	@$(UVX) $(RHIZA_TASK) list
	@printf '\nRepo-owned targets (this file):\n'
	@grep -hE '^[a-zA-Z0-9_-]+:.*##' $(MAKEFILE_LIST) | sed -e 's/:.*##/ -- /' -e 's/^/  /'

# `%:` matches any target make cannot otherwise resolve. Two caveats, both survivable: a
# typo is routed here too (the CLI's "unknown task" error is the backstop), and a task
# needing flags wants `uvx rhiza-task <task> --flag` directly. `.PHONY` cannot name unknown
# targets, so a *file* sharing a task's name would shadow it -- none do.
%: $(UVX)
	@$(UVX) $(RHIZA_TASK) $@

# Named as a file rather than a phony `install-uv`, so make's own up-to-date check is the
# idempotence: when uvx is on PATH this is an existing file with no prerequisites and
# nothing runs, and when it is not, this rule is the only way the file can come into being.
# There is no probe to get wrong and no second invocation that re-downloads.
#
# The target is `$(UVX)` and not `$(INSTALL_DIR)/uvx` because it has to exist as an
# explicit rule in *both* cases: with no rule of its own, an on-PATH uvx is matched by the
# catch-all below, whose prerequisite is that same file, and every invocation opens with
# `make: Circular /usr/local/bin/uvx <- /usr/local/bin/uvx dependency dropped.`
#
# `$(@D)` rather than `$(INSTALL_DIR)`: the installer writes where the binary was expected,
# so an overridden `UVX=/somewhere/uvx` provisions /somewhere rather than silently
# downloading to ./bin and then running nothing.
$(UVX):
	@echo "[INFO] uv not found; installing into $(@D)"
	@curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR="$(@D)" sh >/dev/null

# Repo-specific one-offs live here, where they always belonged, and win over the catch-all
# because an explicit rule beats a pattern rule. This is what `local.mk` was for -- and a
# repository that carried its *own* fragment under `.rhiza/make.d/` moves it here, since
# nothing includes that folder any more.
-include local.mk

# An included makefile is also a target make tries to *remake* before running anything, and
# with a match-anything rule in scope that attempt is routed to the CLI -- so every single
# invocation used to begin with "unknown task: local.mk". An explicit rule with an empty
# recipe satisfies the remake attempt silently.
local.mk: ;

# The Makefile needs the same treatment now, and did not before. A match-anything rule with
# no prerequisites cannot make an existing Makefile out of date, so the remake attempt was a
# no-op; `$(UVX)` is a prerequisite that a cold checkout *creates*, which makes it newer than
# the Makefile, which makes the Makefile out of date -- so make remade it by running
# `uvx rhiza-task Makefile`, and the first `make <anything>` on a machine without uv died
# with "unknown task: Makefile" right after installing uv. An empty recipe ends that too.
Makefile: ;

# ==============================================================================
# Mother-repo-only targets (rhiza itself)
#
# These were `.rhiza/make.d/bundles.mk`, a fragment no bundle shipped. They land here
# rather than in `local.mk` for one reason: `local.mk` is gitignored (.gitignore:121) and
# CI invokes one of them — `make e2e` from rhiza_e2e.yml — so they need a committed home.
# An explicit rule beats the `%:` pattern rule above, so they take precedence over the CLI
# delegation; `install` as a prerequisite still resolves through it.
#
# The folder accumulators this fragment also carried (TYPECHECK_FOLDERS, BANDIT_FOLDERS,
# DOCSTRING_FOLDERS, DEPTRY_FOLDERS, SEMGREP_FOLDERS, COVERAGE_FOLDERS += utils) are gone,
# replaced by `source-folder = "utils"` in pyproject.toml's [tool.rhiza-task]. They existed
# because this repo ships configuration and has no src/, so SOURCE_FOLDER matched nothing
# and five gates measured nothing (#1505, #1511, #1516). The CLI reads a single
# source_folder, and `utils` is this repo's only non-test Python, so one setting replaces
# six appends. tests/utils/test_gate_scope.py pins the outcome either way.
# ==============================================================================

.PHONY: explain-bundles sync-self sync-self-check e2e rhiza-test

# `uv` as well as `uvx`: the astral installer writes both into the same directory, so once
# $(UVX) exists this does too. The empty recipe satisfies make's remake attempt, the same
# trick the shim uses for `local.mk`.
UV ?= $(shell command -v uv 2>/dev/null || echo $(INSTALL_DIR)/uv)
$(UV): $(UVX) ;

# Which end-to-end modules `make e2e` runs. One per language layer, so CI can give each its
# own job (and its own toolchain) by narrowing this:
#   make e2e E2E_ARGS=tests/e2e/test_go_layer_e2e.py
E2E_ARGS ?= tests/e2e

explain-bundles: $(UV) ## print all bundles and profiles with descriptions and dependencies
	@$(UV) run utils/explain_bundles.py

sync-self: $(UV) ## relink root dogfood copies as symlinks into bundles/ (mother repo only)
	@$(UV) run utils/link_dogfood.py

# The local drift check, for use before committing a new bundle file. In CI the same
# invariant is asserted by tests/bundles/test_bundle_dogfood_symlinks.py inside `make test`
# — using link_dogfood's own carve-out predicate and bundle index, so the two cannot
# disagree. No workflow runs this target (#1532).
sync-self-check: $(UV) ## fail if any dogfood symlink is stale/missing without writing (local drift check)
	@$(UV) run utils/link_dogfood.py --check

# The language-layer end-to-end suite: assemble a profile into a temp directory, scaffold
# the smallest project the layer should be green on, and run every gate for real. Opt-in
# because it drives real toolchains and takes minutes per layer; a layer whose compiler is
# absent skips rather than fails, so `make e2e` on a machine with no Go installed still
# exercises the layers it can.
#
# `make test` deliberately excludes it: the matrix would pay for it on every OS and Python
# version. .github/workflows/rhiza_e2e.yml is where all three actually run.
#
# pytest-timeout is provisioned here rather than declared: without it pytest ignores both
# pytest.ini's `timeout` and the suite's marker — silently, so a hung gate would run until
# the CI job's own timeout killed it with no indication of which gate hung.
e2e: install $(UV) ## run the language-layer end-to-end suite against real toolchains (opt-in)
	@printf "\033[36m[INFO] Running end-to-end suite: $(E2E_ARGS)\033[0m\n"
	@RHIZA_E2E=1 $(UV) run --with pytest-timeout pytest $(E2E_ARGS) -v

# `rhiza-test` is wrapped rather than delegated. As of 0.3.1 the wrapper no longer *fixes*
# anything; it is what makes the fix assertable here.
#
# pytest-rhiza's `test_docstrings` takes its scope from the RHIZA_DOCTEST_FOLDERS
# environment variable, falling back to SOURCE_FOLDER in `.rhiza/.env` and then to `src`.
# `quality.mk` used to export it from DOCSTRING_FOLDERS; rhiza-task 0.3.0 did not, so on a
# bare delegation the check reported
#
#   SKIPPED  No doctest folder found (looked for: src)
#
# and the gate still said `ok rhiza-test` — #1517 exactly: this repo's only doctest examples
# unchecked, silently, behind a green gate. `.rhiza/.env` cannot carry the value because that
# file is gitignored, so CI would never see it.
#
# rhiza-task 0.3.1 passes `source_folder` through as that variable itself
# (Jebel-Quant/rhiza-task#18), so this recipe now exports the value the CLI would export
# anyway — same folder, from the same setting. It stays because it is where the property can
# be checked cheaply: tests/utils/test_gate_scope.py reads the expanded variable out of a
# `make -n`, needing no network, no lockfile and no tags, and fails if the export goes. A
# bare delegation moves the property inside the pin, where only a real run reveals it.
rhiza-test: $(UVX) ## run the rhiza repository checks, with this repo's doctest scope
	@RHIZA_DOCTEST_FOLDERS="$(shell $(UVX) $(RHIZA_TASK) print source_folder)" \
		$(UVX) $(RHIZA_TASK) rhiza-test
