"""Gates for gh-aw agentic workflow lock files.

CLAUDE.md and docs/development/GH_AW.md mandate that every agentic workflow
``.md`` source in ``.github/workflows/`` is compiled to a committed
``.lock.yml`` (via ``make gh-aw-compile``) and that both are committed
together. The CI-side check (``rhiza_gh-aw-validate.yml``) only runs when a
``.md`` file changes and the gh-aw extension is installable, so these tests
gate the invariant on every run:

1. every agentic ``.md`` source has a committed ``.lock.yml`` sibling, and
2. the lock file is fresh — its embedded ``body_hash`` (sha256 of the
   stripped markdown body, recorded by ``gh aw compile`` in the
   ``gh-aw-metadata`` header line) matches the current source.

Frontmatter-only edits are not caught here (gh-aw normalises frontmatter
before hashing); those are still covered by the recompile-and-diff check in
``rhiza_gh-aw-validate.yml``.
"""

import hashlib
import json
import re
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
_WORKFLOWS = _ROOT / ".github" / "workflows"

_FRONTMATTER = re.compile(r"^---\n.*?\n---\n(?P<body>.*)$", re.DOTALL)
_METADATA_LINE = re.compile(r"^#\s*gh-aw-metadata:\s*(?P<json>\{.*\})\s*$")


def _agentic_sources() -> list[Path]:
    """Return the agentic workflow sources: .md files with YAML frontmatter."""
    return sorted(path for path in _WORKFLOWS.glob("*.md") if _FRONTMATTER.match(path.read_text(encoding="utf-8")))


def _lock_metadata(lock_file: Path) -> dict:
    """Parse the gh-aw-metadata JSON from the first line of a lock file."""
    first_line = lock_file.read_text(encoding="utf-8").splitlines()[0]
    match = _METADATA_LINE.match(first_line)
    assert match, (
        f"{lock_file.name}: first line is not a gh-aw-metadata header — "
        "the file was not generated by `make gh-aw-compile`"
    )
    return json.loads(match.group("json"))


def test_agentic_sources_exist():
    """Sanity check: the repository ships agentic workflow .md sources."""
    assert len(_agentic_sources()) >= 3, f"expected at least 3 agentic workflow sources, found {_agentic_sources()}"


@pytest.mark.parametrize("source", _agentic_sources(), ids=lambda p: p.name)
def test_every_agentic_source_has_a_committed_lock_file(source: Path):
    """Every .github/workflows/*.md agentic source must have a .lock.yml sibling."""
    lock_file = source.with_suffix("").with_suffix(".lock.yml")
    assert lock_file.is_file(), (
        f"{source.name} has no committed {lock_file.name}. "
        "Run `make gh-aw-compile` and commit the .md and .lock.yml together."
    )


@pytest.mark.parametrize("source", _agentic_sources(), ids=lambda p: p.name)
def test_lock_file_is_fresh(source: Path):
    """The lock file's recorded body hash must match the current .md body."""
    lock_file = source.with_suffix("").with_suffix(".lock.yml")
    if not lock_file.is_file():
        pytest.skip("missing lock file is reported by test_every_agentic_source_has_a_committed_lock_file")

    metadata = _lock_metadata(lock_file)
    body = _FRONTMATTER.match(source.read_text(encoding="utf-8")).group("body")
    body_hash = hashlib.sha256(body.strip().encode("utf-8")).hexdigest()
    assert body_hash == metadata.get("body_hash"), (
        f"{lock_file.name} is stale: its gh-aw-metadata body_hash does not match {source.name}. "
        "Run `make gh-aw-compile` and commit the updated lock file."
    )


def test_gh_aw_compile_did_not_clobber_dependabot_config():
    """`gh aw compile` rewrites .github/dependabot.yml with its own content.

    The Dependabot configuration is owned by this repository (and deliberately
    kept as-is — see #1152), not by the gh-aw compiler. The rewrite strips the
    rhiza header; gate on the header and on lockstep with the github bundle's
    copy so a clobbered file cannot be committed unnoticed after running
    `make gh-aw-compile`.
    """
    root_copy = _ROOT / ".github" / "dependabot.yml"
    bundle_copy = _ROOT / "bundles" / "github" / ".github" / "dependabot.yml"
    content = root_copy.read_text(encoding="utf-8")
    assert content.startswith("# This file is part of the jebel-quant/rhiza repository"), (
        ".github/dependabot.yml lost its rhiza header — most likely rewritten by `gh aw compile`. "
        "Restore it with `git checkout .github/dependabot.yml`."
    )
    assert content == bundle_copy.read_text(encoding="utf-8"), (
        ".github/dependabot.yml and bundles/github/.github/dependabot.yml differ — keep them in lockstep."
    )
