#!/usr/bin/env python3
"""Generate a coverage badge JSON file from pytest coverage data.

This script reads coverage.json generated by pytest-cov and creates a
shields.io compatible badge JSON file with appropriate color coding based
on coverage percentage.

Usage:
    python generate_coverage_badge.py <input_coverage.json> <output_badge.json>
"""

import json
import sys
from pathlib import Path


def get_badge_color(percentage: int) -> str:
    """Determine badge color based on coverage percentage.
    
    Args:
        percentage: Coverage percentage (0-100)
        
    Returns:
        Color name for shields.io badge
    """
    if percentage >= 90:
        return "brightgreen"
    elif percentage >= 80:
        return "green"
    elif percentage >= 70:
        return "yellow"
    elif percentage >= 60:
        return "orange"
    else:
        return "red"


def generate_badge(coverage_json_path: Path, output_json_path: Path) -> None:
    """Generate coverage badge JSON from coverage data.
    
    Args:
        coverage_json_path: Path to coverage.json from pytest-cov
        output_json_path: Path where badge JSON should be written
        
    Raises:
        FileNotFoundError: If coverage JSON file doesn't exist
        KeyError: If coverage JSON is missing required fields
    """
    if not coverage_json_path.exists():
        raise FileNotFoundError(f"Coverage file not found: {coverage_json_path}")
    
    # Read coverage data
    with open(coverage_json_path) as f:
        coverage_data = json.load(f)
    
    # Extract coverage percentage
    try:
        percentage = int(coverage_data["totals"]["percent_covered"])
    except KeyError as e:
        raise KeyError(f"Invalid coverage JSON format: missing {e}")
    
    # Create badge data
    badge = {
        "schemaVersion": 1,
        "label": "coverage",
        "message": f"{percentage}%",
        "color": get_badge_color(percentage),
    }
    
    # Ensure output directory exists
    output_json_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Write badge JSON
    with open(output_json_path, "w") as f:
        json.dump(badge, f, indent=2)
    
    print(f"✓ Coverage badge generated: {percentage}% ({badge['color']})")
    print(f"  Saved to: {output_json_path}")


def main() -> int:
    """Main entry point.
    
    Returns:
        Exit code (0 for success, 1 for error)
    """
    if len(sys.argv) != 3:
        print("Usage: generate_coverage_badge.py <input_coverage.json> <output_badge.json>")
        return 1
    
    coverage_json_path = Path(sys.argv[1])
    output_json_path = Path(sys.argv[2])
    
    try:
        generate_badge(coverage_json_path, output_json_path)
        return 0
    except (FileNotFoundError, KeyError) as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
